### PR TITLE
Merge 0.16

### PR DESCRIPTION
**Pull request by remotevase**
> ## **DO NOT DELETE THE FOLLOWING**

> ### PR Description

> - Edit this text for description!

> ### Sources:

> - ERROR: Edit This Text To Include PR Sources (Pictures Errors ETC)

> ### Please provide all that apply to this Issue!
- [ ] This PR isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [ ] This PR includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [ ] This PR is written in your native language for maximal clarity
- [ ] This PR does not have abbreveations. Abbreviations make it not understandable.
- [ ] This PR is for ImagicalMine, and not any other server software
- [ ] This PR Is tested

> ### Refrences:

> - Edit this text to refrence an Issue that should be fixed by this PR (EX: Issue #13834391)

#DO NOT MERGE YET!

### CODE REVIEW

**Comment by DarkWav** [comment]
I gonna merge this now.
I´ll update the protocol with ORIGINAL POCKETMINE PROTOCOL. (this is a FORK of PocketMine-MP, so i guess we can copy from it i think so...)  were just too dumb for coding....

**Comment by DarkWav** [comment]
this was actually.... merged... had too many confilicts.

**Comment by WarenGonzaga** [comment]
I'm gonna try to help you guys...

**Comment by remotevase** [comment]
okay, thanks @WarenGonzaga

**Pull request closed without merging**
