### PR TITLE
fix rakib block 5 seconds

### PR DESCRIPTION
**Pull request by caspervanneck**
> ## **DO NOT DELETE THE FOLLOWING**

> ### PR Description

> - Edit this text for description!

> ### Sources:

> - ERROR: Edit This Text To Include PR Sources (Pictures Errors ETC)

> ### Please provide all that apply to this Issue!
- [ ] This PR isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [ ] This PR includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This PR is written in your native language for maximal clarity
- [ ] This PR does not have abbreveations. Abbreviations make it not understandable.
- [ ] This PR is for ImagicalMine, and not any other server software
- [x] This PR Is tested

> ### Refrences:

> - Edit this text to refrence an Issue that should be fixed by this PR (EX: Issue #13834391)

you can now join ImagicalMine

### CODE REVIEW

**Comment by caspervanneck** [comment]
you can now join ImagicalMine @remotevase

**Comment by caspervanneck** [comment]
fixt it for you

**Comment by Sandertv** [comment]
Does it actually work??

**Comment by caspervanneck** [comment]
no player crash

**Comment by caspervanneck** [comment]
somting with level

**Comment by caspervanneck** [comment]
but conect work i can conect @Sandertv

**Comment by DarkWav** [comment]
ill test it out. thanks

**Pull request merged**
