### PR TITLE
Removing the line breaks...

### PR DESCRIPTION
**Pull request by iPocket**
> ## **Pull Request**

> ### PR Description

> Too many extra BRs that will make anyone not use this

> ### Sources:

> - No sources

> ### Please provide all that apply to this Issue!
- [x] This PR isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This PR includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [ ] This PR is written in your native language for maximal clarity
- [x] This PR does not have abbreveations. Abbreviations make it not understandable.
- [x] This PR is for ImagicalMine, and not any other server software
- [x] This PR Is tested

> ### Refrences:

> - No references

### CODE REVIEW

**Comment by remotevase** [comment]
Use the Quicklinks

**Comment by Taki21** [comment]
@remotevase its better to remove the extra space:
1. By using quick links is professional but if you make all the links so apart and with so much empty space it doesnt seem professional. 
2. Some people prefer to scroll down for whatever reason 
3. For some browsers OR some clients: The page will take too much time too load and might give a GitHub loading error.

**Comment by iPocket** [comment]
I actually can't scroll properly with that small long scroller, and that makes this page like spam.

**Comment by iPocket** [comment]
also it will be harder for others to read.

**Comment by Taki21** [comment]
It can also screw ur ram

**Comment by remotevase** [comment]
oh, u guys make good points

**Pull request merged**
